INSERT INTO SCORE_BY_LEVEL (LEVEL, SCORE) VALUES ('A', 5);
INSERT INTO SCORE_BY_LEVEL (LEVEL, SCORE) VALUES ('B', 10);
INSERT INTO SCORE_BY_LEVEL (LEVEL, SCORE) VALUES ('C', 15);
INSERT INTO SCORE_BY_LEVEL (LEVEL, SCORE) VALUES ('Cuauh', 20);